version: '3'

services:
# Add the whoami service
  whoami:
     # A container that exposes an API to show its IP address
     image: containous/whoami
     # We set a label to tell Traefik to assign a hostname to the new service
     labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"
      #- "traefik.http.services.whoami.loadbalancer.server.port=5000" # You choose which port should be used by traefik to pass the requests
     networks:
      - traefiknet
networks:
  traefiknet:
    external: true
