version: '3'

services:
  traefik:
    # The latest official supported Traefik docker image
    image: traefik:v2.11
    # Enables the Traefik Dashboard and tells Traefik to listen to docker
    # --providers tell Traefik to connect to the Docker provider
    # enable --log.level=INFO so we can see what Traefik is doing in the log files
    ports:
      # Exposes port 80 for incomming web requests
      - "80:80"
      # The Web UI port http://0.0.0.0:8080 (enabled by --api.insecure=true)
      - "127.0.0.1:8080:8080"
      - "443:443"
    volumes:
      - /opt/traefik/:/etc/traefik/
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
     - traefiknet
networks:
  traefiknet:
    external: true
